sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t viniciuscosta/docker-react-boilerplate -f Dockerfile.dev .

script:
  - docker run -e CI=true viniciuscosta/docker-react-boilerplate npm run test -- --coverage
