sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t viniciuscosta/docker-react-boilerplate -f Dockerfile.dev .

script:
  - docker run -e CI=true viniciuscosta/docker-react-boilerplate npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-west-2-933272758573"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
